language: node_js
node_js:
- 6
deploy:
  provider: heroku
  api_key:
    secure: Wx44djrsOYrOcOpBWHHhrRK46sUnOuwuVB74QQeZwnf7yaUfoXTu8qWqvOyhCwYKUN71qhi2muF8Ad8q+M/V1Kw2MI4bDcQBOkCVtK0qusK9BULvSfC+G2oBjCIeOWJziWfWTQF/ntiAXIYAX2hDTJXn7np1/EYLLvG51tXnE4/YnuPf2yFdBRjCnB1xOQlpBvU041ENXwkfNwPWMgyQhlrF2IdC6bD2i58K2BFnT7r6kCytOqj1cQunmsC833uhbBnwWZsm3SJEhnEaUP24t/NNr9TXWKc3QpD02J072DmXvWkKYDKN36Eq7PkxgULHpjb0ZmnSNL0UKzudNPqrX1iru48i0rQ+o+XgIoo8wgv/3ObXZpv0NlKd2/PlswOlWMFebYjgisx4O7FtB9DAV2yYe/bsULKzadQNDGdtC4LFNBadY6UgFzPh3/b8dnyTmHx3bVlGTkhYTdfqSOcFj/LwNKTyIFZ1vzJ76pUQGHirLhKrhRRRw2QHjXafW20D0YU+cyzeVX/Gi0VzH4zY2dP/KQMoyX7be6HypNMXbdsfaPkNyU3EplAgrZie0qsyg/jG92VG42tlor2DZkblXTktAKXk9MLXtkaE8WhTob+vsF0wbIDJMQU5bXznn3PDNvBZDJxRz/ePuRd6ELU/N6AufeautgsfPkRiR9WkDTk=
  app: my-first-deploy
